spring.application.name=position

server.port = ${SERVER_PORT}

spring.datasource.url = ${CUSTOM_DATASOURCE_URL}
spring.datasource.username = ${CUSTOM_DATASOURCE_USERNAME}
spring.datasource.password = ${CUSTOM_DATASOURCE_PASSWORD}

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
